BOX_IMAGE = "ubuntu/bionic64"
ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  #https://stackoverflow.com/questions/37556968/vagrant-disable-guest-additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  config.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
  config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false
  config.vm.define "inception" do |control|
    #https://stackoverflow.com/questions/18528717/vagrant-shared-and-synced-folders
    control.vm.synced_folder ".", "/vagrant", disabled: true
    control.vm.hostname = "inception"
    control.vm.network "private_network", ip: "192.168.42.110"
    control.vm.provision :shell, privileged: true, path: "./server.sh"

    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.cpus = 1
      v.memory = 1024
    end
  end
end

